# `tidyfun`

The goal of tidyfun is to provide a `tidyverse`-compliant, accessible and well-documented way to deal with functional data, specifically for data wrangling and exploratory analysis.  

## New vector-like data types for functional data

`tidyfun` provides new `S3`-classes for functional data, either as raw data (class `tfd` for *t*idy *f*unctional *d*ata) or in basis representation (class `tfb` for *t*idy *f*unctional *b*asis data).  
Both are represented internally as lists, so they work well as columns in data frames. That makes it a lot easier to keep conventional data and functional measurements together in one object for preprocessing, exploratory analysis and description.  
At the same time, they actually behave like vectors of *functions**, i.e. they can be evaluated on any point of their domain, integrated or differentiated, etc.:

```r
arg <- seq(0, 2, l = 51)
values <- rbind(arg^2, log1p(arg), sin(3*arg))
f <- tfd(values, arg = arg) 
f
str(as.data.frame(f))
all(as.matrix(f) == values)
plot(f)
```
```r
# evaluate anywhere:
f[, c(0.02, 1.1)]
# compute:
2*f
log(f)
# summarize (point-wise or across the function):
mean(f)
depth(f)

# integrate / differentiate
integrate(f)
deriv(f)

#query
where(f, value < 0.3 & arg > .3)
```

## Pipe-friendly `tidyverse` verbs for dealing with functional data inside data frames

`tidyfun` provides `tf_gather` & `tf_spread`, `tf_nest` & `tf_unnest`
in order to quickly and easily create, reshape and transform functional data columns 

```r
# data.frame with functional data as matrix column:
str(data <- refund::DTI[, c(1:2, 5, 8)])
# convert to tfd-column
glimpse(data <- as.tbl(tf_gather(data, cca)))
# spread out into separate columns:
(data <- tf_spread(data, cca, arg = seq(1, 93, by = 3)))
# re-collect columns into one tfd-column:
glimpse(data <- tf_gather(data, matches("cca")))
# make long format data frame with one row for each function evaluation:
glimpse(data <- tf_unnest(data, cca))
# re-collect rows for each function evaluation into tfd column and shorter table:
glimpse(data <- tf_nest(data, matches("cca")))
```

## New geoms and stats for functional data for customizable `ggplot2` graphics

```r
# find healthy controls (case = 0) with high CCA:
data <- data %>% rename(cca = cca_value)
data %>% filter(case == 0 &  (integrate(cca - mean(cca)) > 4)) %>% glimpse
data <- mutate(data, cca_dev = integrate(cca - mean(cca)))
ggplot(data) + geom_spaghetti(aes(tf = cca, col = cca_dev)) + 
  geom_meatballs(filter(data, cca_dev > 4), aes(tf = cca), noodles = FALSE) + 
  facet_grid(~case)
```




## Installation

You can install tidyfun from github with:

``` r
devtools::install_github("fabian-s/tidyfun")
```

## Example

```{r}
library(tidyverse)

dti <- refund::DTI
str(dti)

f_cca <- feval(dti$cca, argvals = seq(0, 1, l = 93))
f_cca

test <- with(dti, data_frame(id = ID, sex = sex, cca = f_cca))
test

# select patient-visits with CCA-FA at location .7 greater than .6
test %>% filter(cca[, .7, raw = TRUE] > .6)
# select patient-visits with maximal CCA-FA over location interval [.7, 1]  greater than .8
test %>% filter(apply(cca[, seq(.7, 1, l = 50), raw = TRUE], 1, max) > .8)

unnest(test, .sep = "_")
unnest(test, .sep = "_", .argvals = seq(0, 1, l = 93)[1:5])

```
